// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Tz5sJNOkqIBs_c8NVDf0ftS29DlKO5Y',
    appId: '1:835052484226:web:f02af749bd94b1b698669b',
    messagingSenderId: '835052484226',
    projectId: 'robot-tutor',
    authDomain: 'robot-tutor.firebaseapp.com',
    storageBucket: 'robot-tutor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHc8Nh2z5Zr5tdoWIlTsnaq-bXj9nTjHQ',
    appId: '1:835052484226:android:d1692cea07276c8998669b',
    messagingSenderId: '835052484226',
    projectId: 'robot-tutor',
    storageBucket: 'robot-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsUL2TBbMVu2h8fS8Py4FQ9EUI4AFxlkU',
    appId: '1:835052484226:ios:5d8cfda261d364b098669b',
    messagingSenderId: '835052484226',
    projectId: 'robot-tutor',
    storageBucket: 'robot-tutor.firebasestorage.app',
    iosBundleId: 'com.example.robotTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsUL2TBbMVu2h8fS8Py4FQ9EUI4AFxlkU',
    appId: '1:835052484226:ios:5d8cfda261d364b098669b',
    messagingSenderId: '835052484226',
    projectId: 'robot-tutor',
    storageBucket: 'robot-tutor.firebasestorage.app',
    iosBundleId: 'com.example.robotTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Tz5sJNOkqIBs_c8NVDf0ftS29DlKO5Y',
    appId: '1:835052484226:web:e11691bf043fca0298669b',
    messagingSenderId: '835052484226',
    projectId: 'robot-tutor',
    authDomain: 'robot-tutor.firebaseapp.com',
    storageBucket: 'robot-tutor.firebasestorage.app',
  );
}
